Repository toptal/davinci-github-actions, pull requests merged in 2022-11, with the labels that each got.

#58 [MAT-1783] GHA to check if there are untracked GQL types
  .changeset/five-bags-tickle.md
  .github/workflows/pr-checks.yml
  no-untracked-generated-types/README.md
  no-untracked-generated-types/action.yml
Labels: github-actions, contribution, Matrix

#64 fix: incorrect reference to path-pattern
  .changeset/red-waves-provide.md
  no-untracked-generated-types/action.yml
Labels: Matrix

#66 Update README.md for no-untracked-generated-types
  no-untracked-generated-types/README.md
Labels: no-jira, contribution

#70 ci: add image push to gar
  build-push-image/action.yml
Labels: contribution

#71 chore: add changeset
  .changeset/sharp-masks-beam.md
Labels: no-jira

#73 chore(deps): add lodash to resolutions
  package.json
  yarn.lock
Labels: dependencies
