Repository toptal/davinci-github-actions, pull requests merged in 2023-11, with the labels that each got.

#229 [CI] Add GSM actions to public repos
  expose-json-outputs/README.md
  expose-json-outputs/action.yml
  expose-json-outputs/dist/index.js
  expose-json-outputs/src/index.js
  gsm-secrets/README.md
  gsm-secrets/action.yml
Labels: no-jira, github-actions, contribution

#230 chore: add changeset for gsm actions
  .changeset/sweet-rules-try.md
Labels: no-jira, contribution

#236 Fix docs in pr-conventional-to-toptal-commits
  pr-conventional-to-toptal-commits/README.md
Labels: no-jira

#240 [CI-2922] Update workflows to fetch secrets from GSM
  .changeset/chilled-turkeys-exist.md
  .github/workflows/handle-contribution.yml
  .github/workflows/release.yml
  .gitignore
Labels: contribution
