Repository toptal/davinci-github-actions, pull requests merged in 2023-02, with the labels that each got.

#110 Bump version build push release image
  .changeset/famous-apricots-live.md
  build-push-release-image/action.yml
Labels: contribution

#103 fix: contribution action
  .changeset/healthy-items-happen.md
  notify-jira-about-contribution/action.yml
  notify-jira-about-contribution/notify-jira.sh
Labels: no-jira

#113 Address deprecated commands
  .changeset/green-papayas-stare.md
  build-push-release-image/action.yml
  get-workflow-sha/action.yml
Labels: contribution

#117 feat: add action to get slack name based on email
  .changeset/fresh-crabs-cheat.md
  get-user-slack-from-email/README.md
  get-user-slack-from-email/action.yml
  yarn-install/README.md
Labels: no-jira, contribution, DO NOT MERGE

#123 fix: wrong JSON format sent to JIRA
  .changeset/good-clouds-think.md
Labels: no-jira
