Repository toptal/davinci-github-actions, pull requests merged in 2024-06, with the labels that each got.

#321 Bump google-github-actions/get-secretmanager-secrets to v2
  .changeset/beige-monkeys-type.md
  gsm-secrets/action.yml
Labels: no-jira, dependencies, contribution

#324 Make actions to work with runner-sets
  .changeset/spotty-pears-hope.md
  build-push-image/action.yml
  yarn-install/action.yml
Labels: no-jira, contribution

#326 CI fixup yarn-install
  .changeset/nervous-hotels-raise.md
  build-push-image/action.yml
  yarn-install/action.yml
Labels: bug, no-jira

#331 [Fx-NULL] Add ability to ignore certain major update packages
  .changeset/tame-comics-agree.md
  notify-jira-about-contribution/README.md
  notify-jira-about-contribution/action.yml
  notify-jira-about-contribution/should-create-jira-issue.sh
  notify-jira-about-contribution/should-create-jira-issue.test.sh
Labels: no-jira

#334 [GE-1005] Fix node deprecation warnings in Yarn Install action
  yarn-install/action.yml
Labels: contribution
