Repository toptal/davinci-github-actions, pull requests merged in 2024-02, with the labels that each got.

#274 Disable NPM proxy
  yarn-install/action.yml
Labels: no-jira, contribution

#275 [FX-NULL] Release latest changes
  .changeset/silly-rivers-hope.md
Labels: no-jira

#281 [CI] Make build-publish-alpha-package work with custom runners
  .changeset/stupid-lions-obey.md
  build-publish-alpha-package/action.yml
Labels: contribution

#282 Add npm proxy variable
  .changeset/few-swans-rush.md
  yarn-install/action.yml
Labels: contribution

#280 [FX-4878] Fix major version detection
  .changeset/curvy-cows-promise.md
  notify-jira-about-contribution/README.md
  notify-jira-about-contribution/action.yml
  notify-jira-about-contribution/should-create-jira-issue.sh
  notify-jira-about-contribution/should-create-jira-issue.test.sh
Labels: no-jira

#289 Remove NPM proxy variable from yarn-install action
  .changeset/great-mails-melt.md
  yarn-install/action.yml
Labels: no-jira, contribution
